version: "3.7"

services:
  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Zeto.2003
      - MYSQL_DATABASE=vegeboxDB
    ports:
      - 3306:3306

  app:
    image: hanggoroseto6460/vegebox:latest
    restart: always
    depends_on:
      - database-vegebox
    ports:
      - 1323:1323/tcp
